Сhanged the application with Clean Architecture
Bugorek/65apps pull request #10
Opened 2021-05-03 16:36 UTC by Bugorek

Редактирование проекта с учетом Clean Architecture. Бизнес-логика перенесена в Interactor. Использовано правило зависимостей.

2021-05-04 16:16 UTC, murrcha requested changes
необходимо разделить на 3 отдельных модуля:
application
domain
presentation
в соответствии с заданием

2021-06-23 14:03 UTC, murrcha commented on application/build.gradle
> +    implementation 'com.google.android.material:material:1.3.0'
возможно используются лишние зависимости, лучше убрать, к примеру, material - для presentation

2021-06-23 14:05 UTC, murrcha commented on application/src/test/java/com/example/application/ExampleUnitTest.kt
> +class ExampleUnitTest {
лучше убрать

2021-06-23 14:06 UTC, murrcha commented on domain/src/androidTest/java/com/example/domain/ExampleInstrumentedTest.kt
> +class ExampleInstrumentedTest {
лучше убрать

2021-06-23 14:08 UTC, murrcha commented on domain/src/test/java/com/example/domain/ExampleUnitTest.kt
> +class ExampleUnitTest {
лучше убрать

2021-06-23 14:10 UTC, murrcha commented on presentation/src/main/java/com/a65apps/pandaananass/tetsapplication/contact_details/BirthdayNotificationHelper.kt
> +            alarmManager.setExact(AlarmManager.RTC_WAKEUP, birthdayCalendar(dayOfBirth = dayOfBirth, monthOfBirth = monthOfBirth).timeInMillis, pendingIntent)
здесь именованные параметры лучше переносить на новую строку, так проще читать

2021-06-23 14:13 UTC, murrcha commented on presentation/src/main/java/com/a65apps/pandaananass/tetsapplication/contact_details/ContactDetailsFragment.kt
> +                ContactDetailsFragment()
можно упростить в целом создание фрагмента с аргументами используя котлин:
```
fun getNewInstance(id: String): ContactDetailsFragment =
    ContactDetailsFragment().apply{
        arguments = bundleOf(
            ARGUMENT_ID to id
        )
    }
```

bundleOf - androidx.core:core-ktx:1.5.0

2021-06-23 14:15 UTC, murrcha commented on presentation/src/main/java/com/a65apps/pandaananass/tetsapplication/contact_details/ContactDetailsPresenter.kt
> +class ContactDetailsPresenter(private val contactDetailsModel: ContactDetailsInteractor): MvpPresenter<ContactDetailsView>(),
Желательно соблюдать порядок методов по видимости:
override
public
protected
private

2021-06-23 14:17 UTC, murrcha commented on presentation/src/main/java/com/a65apps/pandaananass/tetsapplication/contact_details/ContactDetailsPresenter.kt
> +        val intent = Intent(context, AlarmReceiver::class.java)
здесь также можно сконфигурировать Intent через scoped функцию apply

2021-06-23 14:20 UTC, murrcha commented on presentation/src/main/java/com/a65apps/pandaananass/tetsapplication/contact_list/ContactListFragment.kt
> +        val appDelegate = context.applicationContext as ComponentOwner
небезопасный **as**
лучше использовать безопасный
https://kotlinlang.org/docs/typecasts.html#safe-nullable-cast-operator

2021-06-23 14:22 UTC, murrcha commented on presentation/src/main/java/com/a65apps/pandaananass/tetsapplication/contact_list/ContactListFragment.kt
> +            ContactsListDecorator(
можно один раз создать декоратор при создании фрагмента и переиспользовать его при каждом вызове данного коллбека
плюс настройку rv лучше вынести в отдельный метод

2021-06-23 14:23 UTC, murrcha commented on presentation/src/main/java/com/a65apps/pandaananass/tetsapplication/contact_list/ContactListPresenter.kt
> +            mainActivity.supportFragmentManager.findFragmentByTag(PERMISSION_DIALOG_NAME) as AlertDialogFragment
unsafe as

2021-06-23 14:24 UTC, murrcha commented on presentation/src/main/java/com/a65apps/pandaananass/tetsapplication/contact_list/ContactsListAdapter.kt
> +class ContactsListAdapter(private val onContactClick: (ShortContactModel) -> Unit) : ListAdapter<ShortContactModel, ContactsListViewHolder>(
длинные строки, обычно принято ориентироваться на строку до 120 символов

2021-06-23 14:25 UTC, murrcha commented on presentation/src/main/java/com/a65apps/pandaananass/tetsapplication/contact_list/ContactsListAdapter.kt
> +class ContactsListAdapter(private val onContactClick: (ShortContactModel) -> Unit) : ListAdapter<ShortContactModel, ContactsListViewHolder>(
статический анализатор тебе это покажет позже

2021-06-23 14:25 UTC, murrcha commented on presentation/src/main/java/com/a65apps/pandaananass/tetsapplication/contact_list/ContactsListViewHolder.kt
> +            imgAvatar?.setImageURI(contact.photo!!.toUri())
!! - убрать

2021-06-23 14:51 UTC, murrcha requested changes
Оставила комментарии

2021-06-24 05:25 UTC, Bugorek commented on application/src/androidTest/java/com/example/application/ExampleInstrumentedTest.kt
> +class ExampleInstrumentedTest {
Убрал

2021-06-24 05:25 UTC, Bugorek commented on application/src/test/java/com/example/application/ExampleUnitTest.kt
> +class ExampleUnitTest {
Убрал

2021-06-24 05:28 UTC, Bugorek commented on domain/src/androidTest/java/com/example/domain/ExampleInstrumentedTest.kt
> +class ExampleInstrumentedTest {
Убрал

2021-06-24 05:34 UTC, Bugorek commented on presentation/src/main/java/com/a65apps/pandaananass/tetsapplication/contact_details/BirthdayNotificationHelper.kt
> +            alarmManager.setExact(AlarmManager.RTC_WAKEUP, birthdayCalendar(dayOfBirth = dayOfBirth, monthOfBirth = monthOfBirth).timeInMillis, pendingIntent)
Исправил

2021-06-24 05:39 UTC, Bugorek commented on presentation/src/main/java/com/a65apps/pandaananass/tetsapplication/contact_details/ContactDetailsFragment.kt
> +                ContactDetailsFragment()
Исправил

2021-06-24 05:40 UTC, Bugorek commented on presentation/src/main/java/com/a65apps/pandaananass/tetsapplication/contact_details/ContactDetailsPresenter.kt
> +class ContactDetailsPresenter(private val contactDetailsModel: ContactDetailsInteractor): MvpPresenter<ContactDetailsView>(),
Исправил

2021-06-24 05:50 UTC, Bugorek commented on presentation/src/main/java/com/a65apps/pandaananass/tetsapplication/contact_details/ContactDetailsPresenter.kt
> +        val intent = Intent(context, AlarmReceiver::class.java)
Исправил

2021-06-24 05:52 UTC, Bugorek commented on presentation/src/main/java/com/a65apps/pandaananass/tetsapplication/contact_list/ContactListFragment.kt
> +        val appDelegate = context.applicationContext as ComponentOwner
Исправил

2021-06-24 05:53 UTC, Bugorek commented on presentation/src/main/java/com/a65apps/pandaananass/tetsapplication/contact_list/ContactListPresenter.kt
> +            mainActivity.supportFragmentManager.findFragmentByTag(PERMISSION_DIALOG_NAME) as AlertDialogFragment
Исправил

2021-06-24 06:03 UTC, Bugorek commented on presentation/src/main/java/com/a65apps/pandaananass/tetsapplication/contact_list/ContactListFragment.kt
> +            ContactsListDecorator(
Исправил

2021-06-24 06:06 UTC, Bugorek commented on presentation/src/main/java/com/a65apps/pandaananass/tetsapplication/contact_list/ContactsListAdapter.kt
> +class ContactsListAdapter(private val onContactClick: (ShortContactModel) -> Unit) : ListAdapter<ShortContactModel, ContactsListViewHolder>(
Исправил

2021-06-24 06:07 UTC, Bugorek commented on presentation/src/main/java/com/a65apps/pandaananass/tetsapplication/contact_list/ContactsListViewHolder.kt
> +            imgAvatar?.setImageURI(contact.photo!!.toUri())
Убрал

2021-06-24 06:34 UTC, Bugorek commented on application/build.gradle
> +    implementation 'com.google.android.material:material:1.3.0'
Исправил, material используется, остальное постарался убрать

2021-06-24 07:12 UTC, murrcha commented on presentation/src/main/java/com/a65apps/pandaananass/tetsapplication/contact_details/ContactDetailsFragment.kt
> +            ContactDetailsFragment().apply{
`apply{` - нет пробела, можно использовать авто форматирование по горячим клавишам Ctrl+Alt+L

2021-06-24 07:19 UTC, murrcha commented on presentation/src/main/java/com/a65apps/pandaananass/tetsapplication/contact_list/ContactListFragment.kt
> +            ContactsListDecorator(
декоратор создается всегда после создания вью
надо создавать только при создании фрагмента
нужно перенести в другой коллбек
либо инициализировать сразу как val

2021-06-24 07:19 UTC, Bugorek commented on presentation/src/main/java/com/a65apps/pandaananass/tetsapplication/contact_details/ContactDetailsFragment.kt
> +            ContactDetailsFragment().apply{
Исправил, запомню

2021-06-24 07:46 UTC, Bugorek commented on presentation/src/main/java/com/a65apps/pandaananass/tetsapplication/contact_list/ContactListFragment.kt
> +            ContactsListDecorator(
Исправил

2021-06-24 07:54 UTC, murrcha approved these changes

2021-06-24 08:08 UTC, merged