Changed the application with Dagger2
Bugorek/65apps pull request #9
Opened 2021-04-25 09:53 UTC by Bugorek

Добавлена инверсия зависимостей с помощью библиотеки Dagger2

2021-04-25 10:07 UTC, murrcha commented on app/build.gradle
> +    implementation 'com.google.dagger:dagger:2.35'
+ еще одна зависимость нужна для android
 dagger-android
 https://mvnrepository.com/artifact/com.google.dagger/dagger-android

2021-04-25 10:10 UTC, murrcha commented on app/src/main/java/com/a65apps/pandaananass/tetsapplication/app/AppDelegate.kt
> +class AppDelegate : Application() {
Лучше сделать через DaggerApplication

2021-04-25 10:16 UTC, murrcha commented on app/src/main/java/com/a65apps/pandaananass/tetsapplication/di/contacts/ContactListDataModule.kt
> +abstract class ContactListDataModule {
можно просто `interface`

2021-04-25 10:20 UTC, murrcha commented on app/src/main/java/com/a65apps/pandaananass/tetsapplication/fragments/ContactDetailsFragment.kt
> +        val appDelegate = requireActivity().application as AppDelegate
здесь лучше сделать иньекцию с использованием dagger-android

2021-04-25 10:20 UTC, murrcha commented on app/src/main/java/com/a65apps/pandaananass/tetsapplication/fragments/ContactListFragment.kt
> +        val appDelegate = requireActivity().application as AppDelegate
Аналогично

2021-04-25 10:21 UTC, murrcha commented on app/src/main/java/com/a65apps/pandaananass/tetsapplication/presenters/ContactDetailsPresenter.kt
> +    lateinit var contactDataSource: ContactDetailsOwner
нужно избегать иньекций в поля, и использовать иньекции через конструктор

2021-04-25 10:22 UTC, murrcha requested changes
Оставила комментарии

2021-04-25 16:38 UTC, murrcha commented on app/build.gradle
> +    implementation 'com.google.dagger:dagger:2.35'
Решено оставить голый даггер

2021-04-25 16:39 UTC, murrcha commented on app/src/main/java/com/a65apps/pandaananass/tetsapplication/fragments/ContactDetailsFragment.kt
> +        val appDelegate = requireActivity().application as AppDelegate
до super

2021-04-25 16:40 UTC, murrcha commented on app/src/main/java/com/a65apps/pandaananass/tetsapplication/fragments/ContactListFragment.kt
> +        val appDelegate = requireActivity().application as AppDelegate
аналогично, до super

2021-04-25 16:41 UTC, murrcha commented on app/src/main/java/com/a65apps/pandaananass/tetsapplication/presenters/ContactListPresenter.kt
> +    lateinit var contactDataSource: ContactListOwner
тоже через конструктор

2021-04-26 10:30 UTC, Bugorek commented on app/src/main/java/com/a65apps/pandaananass/tetsapplication/di/contacts/ContactListDataModule.kt
> +abstract class ContactListDataModule {
Исправил

2021-04-26 10:31 UTC, Bugorek commented on app/src/main/java/com/a65apps/pandaananass/tetsapplication/fragments/ContactDetailsFragment.kt
> +        val appDelegate = requireActivity().application as AppDelegate
Исправил

2021-04-26 10:31 UTC, Bugorek commented on app/src/main/java/com/a65apps/pandaananass/tetsapplication/fragments/ContactListFragment.kt
> +        val appDelegate = requireActivity().application as AppDelegate
Исправил

2021-04-26 17:06 UTC, Bugorek commented on app/src/main/java/com/a65apps/pandaananass/tetsapplication/presenters/ContactDetailsPresenter.kt
> +    lateinit var contactDataSource: ContactDetailsOwner
Исправил

2021-04-26 17:06 UTC, Bugorek commented on app/src/main/java/com/a65apps/pandaananass/tetsapplication/fragments/ContactDetailsFragment.kt
> +        val appDelegate = requireActivity().application as AppDelegate
Исправил

2021-04-26 17:06 UTC, Bugorek commented on app/src/main/java/com/a65apps/pandaananass/tetsapplication/presenters/ContactListPresenter.kt
> +    lateinit var contactDataSource: ContactListOwner
Исправил

2021-04-26 18:48 UTC, murrcha commented on app/src/main/java/com/a65apps/pandaananass/tetsapplication/di/contacts/ContactListModule.kt
> +        return ContactListPresenter(contactDataSource = contactDataSource)
Если передаем 1 параметр, то нэйминг можно опустить

2021-04-26 18:52 UTC, murrcha commented on app/src/main/java/com/a65apps/pandaananass/tetsapplication/di/contacts/ContactListDataModule.kt
> +    fun setContactRepository(contactDataSource: ContactDataSource): ContactListOwner
можно предоставить эту зависимость в ContactListModule, второй модуль здесь не нужен

2021-04-26 18:53 UTC, murrcha commented on app/src/main/java/com/a65apps/pandaananass/tetsapplication/presenters/ContactDetailsPresenter.kt
> +class ContactDetailsPresenter @Inject constructor(private val contactDataSource: ContactDetailsOwner): MvpPresenter<ContactDetailsView>(), ContactDetailsData {
достаточно длинная строка
```
class ContactDetailsPresenter @Inject constructor(
private val contactDataSource: ContactDetailsOwner
): MvpPresenter<ContactDetailsView>(), ContactDetailsData {
```

2021-04-26 18:55 UTC, murrcha commented on app/src/main/java/com/a65apps/pandaananass/tetsapplication/di/contact/ContactDetailsDataModule.kt
> +    fun setContactRepository(contactDetailsOwner: ContactDataSource): ContactDetailsOwner
аналогично, можно предоставить в модуле ContactDetailsModule

2021-04-26 18:59 UTC, murrcha approved these changes
Все хорошо. Оставила пару комментариев.
PR принят.

Как продвигается курсовая?

В задание по курсовой можно уже оформлять PR с тем что готово.
То есть не обязательно сдавать сразу всю курсовую.
Можно сдавать по частям.

2021-04-28 13:43 UTC, merged